import { TRANSLATIONS } from './catalog'
import { getRuntimeI18nLocale } from './runtime'
import type { Translations } from './types'

/** Fixed client-side wake capture errors owned by the desktop renderer. */
const WAKE_CAPTURE_ERROR_KEYS = {
  'AudioContext unavailable for client wake capture': 'wakeWordClientMicrophoneFailed',
  'getUserMedia unavailable for client wake capture': 'wakeWordClientMicrophoneFailed'
} as const satisfies Record<string, keyof Translations['composer']>

/**
 * Translate only capability errors generated by the renderer's wake capture.
 * Browser/permission diagnostics from the platform remain unchanged so they
 * still tell the user (or support) what the browser reported.
 */
export function localizedWakeCaptureError(translations: Translations, error: unknown): string {
  const raw = error instanceof Error ? error.message : typeof error === 'string' ? error : String(error)
  const message = raw.replace(/^Error:\s*/, '')
  const key = WAKE_CAPTURE_ERROR_KEYS[message as keyof typeof WAKE_CAPTURE_ERROR_KEYS]

  return key ? translations.composer[key] : raw
}

/** Runtime-locale convenience for non-React stores (the wake-word atom). */
export function localizedWakeCaptureErrorNow(error: unknown): string {
  return localizedWakeCaptureError(TRANSLATIONS[getRuntimeI18nLocale()], error)
}
